---
# disable_firewalld/tasks/main.yml

- name: 'Get list of services'
  ansible.builtin.service_facts:

- name: 'Stop the firewalld service'
  ansible.builtin.service:
    name: 'firewalld'
    state: 'stopped'
  when:
    - '"firewalld.service" in services'
    - "services['firewalld.service']['state'] == 'running'"

- name: 'Disable the firewalld service'
  ansible.builtin.service:
    name: 'firewalld'
    enabled: false
  when:
    - '"firewalld.service" in services'
    - "services['firewalld.service']['status'] != 'not-found'"

- name: 'Mask the firewalld service'
  ansible.builtin.service:
    name: 'firewalld'
    masked: 'true'
